### ISSUE TITLE
something lost 

### ISSUE THREAD

**Issue by ligenxun** [fenjuly/ToggleExpandLayout#11]
the 774e497692(com.github.fenjuly:ToggleExpandLayout:774e497692),when i build,find something lost.

the class(com.fenjuly.mylibrary.DropDownLayout) never find.

**Comment by fenjuly** [comment]
show me the log message, please?

**Comment by ligenxun** [comment]
I have solved it.it's the README.md-->Get into your build-->dependencies{compile'com.github.fenjuly:ToggleExpandLayout:774e497692'},this "774e497692" is too low,this version can`t find "DropDownLayout.java",i personally suggest that you can change your README.md.

**Comment by fenjuly** [comment]
sorry for my carelessness.I'll change the README.md

ligenxun notifications@github.com于2016年5月17日周二 14:25写道：

**Comment by weijia-yu** [comment]
I have the same problem, whichi build version should i use?
