### ISSUE TITLE
java.lang.NoSuchMethodError: android.view.View.setElevation

### ISSUE THREAD

**Issue by mfpolat** [fenjuly/ToggleExpandLayout#3]
Demo app is crashing log is here 

Process: com.fenjuly.toggleexpandlayout, PID: 4599
    java.lang.NoSuchMethodError: android.view.View.setElevation
            at com.fenjuly.toggleexpandlayout.MainActivity$1.onOpen(MainActivity.java:36)
            at com.fenjuly.mylibrary.ToggleExpandLayout$1.onAnimationEnd(ToggleExpandLayout.java:93)

**Comment by fenjuly** [comment]
Because the method doesn't work below API 22.Change your API to make demo
work correctly.

mfpolat notifications@github.com于2015年9月4日周五 下午3:06写道：

**Comment by Mo7mud** [comment]
Does this mean that the library won't work on APIs below 22?

**Comment by fenjuly** [comment]
No, I mean the method in the demo. The library could run below 22.

Mohammad notifications@github.com于2016年1月4日周一 17:36写道：

**Comment by Mo7mud** [comment]
Thank you :+1:
