### ISSUE TITLE
gradle build failed

### ISSUE THREAD

**Issue by akashk1992** [fenjuly/ToggleExpandLayout#4]
Error:(48, 13) Failed to resolve: com.github.fenjuly:ToggleExpandLayout:9de3036
Show in File Show in Project Structure dialog

my Project level gradle:
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.0'
        classpath 'com.google.gms:google-services:1.4.0-beta3'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        maven { url "https://jitpack.io" }
        jcenter()
        mavenCentral()
    }
}

My modul level gradle: 
dependencies {
    compile 'com.github.fenjuly:ToggleExpandLayout:774e497692'
}

**Comment by fenjuly** [comment]
I wouldn't find the error :(
paste more log message please.

**Comment by akashk1992** [comment]
Thanks but I solved the issue

**Comment by pawankhandal52** [comment]
akashk1992 can you explain me how to resolve it

**Comment by akashk1992** [comment]
@pawankhandal52  it was my silly mistake, actually I had "gradle" if "offline" mode

**Comment by softwaresunleashed** [comment]
mine is in online mode still i get this error :(
