### ISSUE TITLE
DropDownLayout not scrolling

### ISSUE THREAD

**Issue by vino4all** [fenjuly/ToggleExpandLayout#9]
I'm using **com.fenjuly.mylibrary.DropDownLayout** which contains _10_ **ToggleExpandLayout**. It is not scrolling. How can I enable scrolling so that I can use more number of **ToggleExpandLayout** in the activity.

**Comment by ghost** [comment]
Was this resolved ? I am facing similar issue, can you please let me know how to resolve this ?

**Comment by fenjuly** [comment]
I'm sorry to tell you it can't be scrolled in the activity.

Bhargav-VIT notifications@github.com于2016年7月26日周二 21:31写道：
